algo = input('Digite algo: ')
print('O tipo primitivo de {} é: {}'.format(algo, type(algo)))
print('{} só tem espaços? {}'.format(algo, algo.isspace()))
print('{} só tem números? {}'.format(algo, algo.isnumeric()))
print('{} só tem letras? {}'.format(algo, algo.isalpha()))
print('{} tem números e letras? {}'.format(algo, algo.isalnum()))
print('{} está só em maiúsculo? {}'.format(algo, algo.isupper()))
print('{} está só em minúsculo? {}'.format(algo, algo.islower()))
print('{} está capitalizada? {}'.format(algo, algo.istitle()))
print('{} contém {} caracteres.'.format(algo, len(algo)))
